---
title: Pixel art reveal
hero_image: images/banner.png
description: Roll a ball to reveal your pixel art design.
meta_title: Pixel art reveal
meta_description: Roll a ball to reveal your pixel art design.
keywords:
- unity
- ball
- marble
- 3d
- game
version: 1
listed: false
copyedit: false
last_tested: "2023-06-26"
steps:
  - title: You will make
  - title: Set up your scene
  - title: Draw your pixel art
    completion:
      - engaged
  - title: Reveal the art
  - title: Quick quiz
    completion:
      - internal
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
    completion:
      - external
